### ISSUE TITLE
deepmerge is not a function

### ISSUE THREAD

**Issue by DanteDeRuwe** [gilbarbara/react-range-slider#11]
I was using [react-spotify-web-playback](https://github.com/gilbarbara/react-spotify-web-playback) and came across this issue:

![image](https://user-images.githubusercontent.com/23363437/116869012-2aa76600-ac10-11eb-988a-511c665a82c1.png)

This is because of this line:
https://github.com/gilbarbara/react-range-slider/blob/ed1e9028e4cf699e57d9c9d50d4ccd081067b08d/src/styles.ts#L1

I will open a PR. Just opening this issue to link.

**Comment by gilbarbara** [comment]
hey @DanteDeRuwe 

deepmerge doesn't have a default export, so it needs the star export in Typescript.
The library uses the compiled file in javascript...

**Comment by DanteDeRuwe** [comment]
It's strange, because if I change everything in my node modules to `require('deepmerge').default` for JS and `import deepmerge from 'deepmerge'` for TS, everything works.

**Comment by gilbarbara** [comment]
your project probably has the `esModuleInterop` flag enabled in the tsconfig.
Libraries can't use that because it will require everyone that uses it to have it enabled too.

**Comment by gilbarbara** [comment]
This is probably some configuration on your project since `react-spotify-web-playback` is used by hundreds of projects without this issue.
Try to recreate the error in a codesandbox.

**Comment by RubyBrewsday** [comment]
Hey there @gilbarbara and @DanteDeRuwe were you able to figure out what the problem was? I'm running into a similar issue with this but I'm using ESBuild and am getting the same issue... any guidance would be greatly appreciated!

**Comment by DanteDeRuwe** [comment]
@RubyBrewsday 

> Hey there @gilbarbara and @DanteDeRuwe were you able to figure out what the problem was? I'm running into a similar issue with this but I'm using ESBuild and am getting the same issue... any guidance would be greatly appreciated!

Yeah I just "solved" this locally using an npm package that could patch node_modules locally and write the changes to a file that can be committed to git so that the change would be persisted even when you remove node_modules. Can't remember what the package was called.

**Comment by DanteDeRuwe** [comment]
@RubyBrewsday the package is called `patch-package`. My patch file is here: https://github.com/DanteDeRuwe/spiralfy/blob/master/player/patches/@gilbarbara+react-range-slider+0.6.1.patch

**Comment by RubyBrewsday** [comment]
Ha @DanteDeRuwe so as it turns out, I got the same exact advice from a colleague of mine shortly after posting and also did that 😄 so good to go now but hopefully this will help if others run into the same issue
